#!/usr/bin/env bash
# Hash-locked requirements for the Python tools CI installs, one file per tool.
# The tool's own version comes from tools/versions.env; every transitive
# dependency is pinned with its hashes, and CI installs with
#   python -m pip install --require-hashes --no-deps -r tools/requirements/<tool>.txt
# so a new release of any dependency changes nothing until the locks are
# regenerated, and a tampered download fails the install.
#
#   tools/requirements/lock.sh           regenerate every lock: after bumping
#                                        SLITHER_VERSION, CRYTIC_COMPILE_VERSION,
#                                        HALMOS_VERSION, ZIZMOR_VERSION or
#                                        TYPOS_VERSION, or to take dependency
#                                        fixes
#   tools/requirements/lock.sh --check   fail when a lock no longer pins the
#                                        version in tools/versions.env (CI)
#
# The locks target CI's interpreter and platform (Python 3.13 on x86_64
# Linux). Dependencies are taken only from releases at least a week old, like
# the Dependabot cooldown; the tools themselves are the versions pinned in
# tools/versions.env, however recent. Regenerating needs uv
# (https://docs.astral.sh/uv). The nightly Halmos run installs unlocked on
# purpose, as a canary for the next lock.
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$root"

python_version=3.13
platform=x86_64-unknown-linux-gnu
cooldown_days=7

version() {
  local value
  value=$(sed -n "s/^$1=//p" tools/versions.env)
  [[ -n $value ]] || { echo "error: $1 is missing from tools/versions.env" >&2; exit 1; }
  printf '%s' "$value"
}

# tool -> its top-level requirements, as "package==version" lines.
requirements() {
  case $1 in
    slither)
      echo "slither-analyzer==$(version SLITHER_VERSION)"
      echo "crytic-compile==$(version CRYTIC_COMPILE_VERSION)"
      ;;
    halmos) echo "halmos==$(version HALMOS_VERSION)" ;;
    zizmor) echo "zizmor==$(version ZIZMOR_VERSION)" ;;
    typos) echo "typos==$(version TYPOS_VERSION)" ;;
  esac
}

tools=(slither halmos zizmor typos)

if [[ ${1:-} == --check ]]; then
  status=0
  for tool in "${tools[@]}"; do
    lock="tools/requirements/$tool.txt"
    while read -r pin; do
      if ! grep -q "^${pin} " "$lock" 2>/dev/null; then
        echo "error: $lock does not pin $pin (tools/versions.env); run tools/requirements/lock.sh" >&2
        status=1
      fi
    done < <(requirements "$tool")
  done
  [[ $status -eq 0 ]] && echo "Python tool locks match tools/versions.env"
  exit "$status"
fi

command -v uv >/dev/null 2>&1 || {
  echo "error: uv is required to regenerate the locks: https://docs.astral.sh/uv" >&2
  exit 1
}

utc() { python3 -c "import datetime as d; print((d.datetime.now(d.timezone.utc) - d.timedelta(days=$1)).strftime('%Y-%m-%dT%H:%M:%SZ'))"; }
cutoff=$(utc "$cooldown_days")
now=$(utc 0)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

for tool in "${tools[@]}"; do
  requirements "$tool" >"$tmp/$tool.in"
  # The cooldown applies to dependencies; the pinned tools are exempt.
  exempt=()
  while read -r pin; do exempt+=(--exclude-newer-package "${pin%%==*}=$now"); done <"$tmp/$tool.in"
  uv pip compile --quiet --no-header --generate-hashes \
    --python-version "$python_version" --python-platform "$platform" \
    --exclude-newer "$cutoff" "${exempt[@]}" "$tmp/$tool.in" -o "$tmp/$tool.txt"
  {
    echo "# Generated by tools/requirements/lock.sh from tools/versions.env; do not edit."
    echo "# Python $python_version, $platform; dependencies published before $cutoff."
    sed "s|$tmp/$tool.in|tools/versions.env|" "$tmp/$tool.txt"
  } >"tools/requirements/$tool.txt"
  echo "tools/requirements/$tool.txt: $(grep -c '^[A-Za-z0-9]' "tools/requirements/$tool.txt") packages"
done
